on:
  repository_dispatch:
    types: [preview-command]

jobs:
  package:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deploy
        id: deploy
        uses: msafadieh/deploy-action@master
        with:
          pr-number: ${{ github.event.client_payload.github.payload.issue.number }}
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: | 
            ```
            Done!
            ```
